title: Sample Learning Lab
description: >-
    Course description: Place your course description here...
template:
    name: learninglab-template
    repo: your-learninglab-template
before:
    - type: createIssue
      title: Week 1
      body: 1.1-Week 1 Step 1.md
steps:
    - title: 'Week 1: Week 1 Step 1'
      description: What is JavaScript?
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.2-Week 1 Step 2.md
          files: ['notes.md']
    - title: 'Week 1: Week 1 Step 2'
      description: What are APIs?
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.3-Week 1 Step 3.md
          files: ['js/config.js']
    - title: 'Week 1: Week 1 Step 3'
      description: Let's Get Started
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1.4-Week 1 Step 4.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 1: Week 1 Step 4'
      description: Setting Up Our APIs
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          files: ['notes.md']
    - title: 'Week 1: Feedback'
      description: Provide your feedback for Week 1!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 1-complete.md
        - type: createIssue
          title: Week 2
          body: 2.1-Week 2 Step 1.md
        - type: closeIssue
    - title: 'Week 2: Week 2 Step 1'
      description: This is the Learning Lab content. (2.1)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 2.2-Week 2 Step 2.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 2: Week 2 Step 2'
      description: This is the Learning Lab content. (2.2)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 2.3-Week 2 Step 3.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 2: Week 2 Step 3'
      description: This is the Learning Lab content. (2.3)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 2.4-Week 2 Step 4.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 2: Week 2 Step 4'
      description: This is the Learning Lab content. (2.4)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 2: Feedback'
      description: Provide your feedback for Week 2!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 2-complete.md
        - type: createIssue
          title: Week 3
          body: 3.1-Week 3 Step 1.md
        - type: closeIssue
    - title: 'Week 3: Week 3 Step 1'
      description: This is the Learning Lab content. (3.1)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 3.2-Week 3 Step 2.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 3: Week 3 Step 2'
      description: This is the Learning Lab content. (3.2)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 3: Feedback'
      description: Provide your feedback for Week 3!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 3-complete.md
        - type: createIssue
          title: Week 4
          body: 4.1-Week 4 Step 1.md
        - type: closeIssue
    - title: 'Week 4: Week 4 Step 1'
      description: This is the Learning Lab content. (4.1)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 4.2-Week 4 Step 2.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 4: Week 4 Step 2'
      description: This is the Learning Lab content. (4.2)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 4.3-Week 4 Step 3.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 4: Week 4 Step 3'
      description: This is the Learning Lab content. (4.3)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 4: Feedback'
      description: Provide your feedback for Week 4!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 4-complete.md
        - type: createIssue
          title: Week 5
          body: 5.1-Week 5 Step 1.md
        - type: closeIssue
    - title: 'Week 5: Week 5 Step 1'
      description: This is the Learning Lab content. (5.1)
      event: pull_request.closed
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: feedback.md
          files: ['index.html', 'js/config.js']
    - title: 'Week 5: Feedback'
      description: Provide your feedback for Week 5!
      event: issue_comment.created
      link: '{{ repoUrl }}/issues'
      actions:
        - type: respond
          with: 5-complete.md
        - type: closeIssue
